Repository NHS-South-Central-and-West/CAIP, pull requests merged in 2023-06, with the labels that each got.

#29 Add further details, methodology, code, and contact to main panel tab
  DESCRIPTION
  NEWS.md
  R/app_server.R
  R/app_ui.R
  R/mod_about.R
  R/mod_downloads.R
  R/mod_fft.R
  R/mod_filters.R
  R/mod_gppt.R
  R/mod_methodology.R
  R/utils.R
  inst/app/www/about.Rmd
  inst/app/www/about.html
  manifest.json
  renv.lock
  tests/testthat/test-mod_about.R
Labels: enhancement

#35 Move download buttons to main panel
  DESCRIPTION
  R/mod_downloads.R
  R/mod_fft.R
  R/mod_filters.R
  R/mod_gppt.R
  R/utils.R
  manifest.json
Labels: enhancement

#48 Add loaders/notifications to delayed elements
  DESCRIPTION
  R/app_server.R
  R/app_ui.R
  R/mod_fft.R
  R/mod_filters.R
  R/mod_gppt.R
  inst/app/www/custom.css
  inst/app/www/styles.css
  manifest.json
  renv.lock
Labels: type: enhancement

#51 Develop robust testing procedures and expand code coverage
  tests/testthat/test-fct_fft_data.R
  tests/testthat/test-fct_gpps_data.R
Labels: priority: high, type: enhancement

#52 Clean up and refactor codebase
  NAMESPACE
  R/golem_utils_server.R
  R/golem_utils_ui.R
  R/utils.R
  tests/testthat/test-app.R
  tests/testthat/test-golem-recommended.R
  tests/testthat/test-golem_utils_server.R
  tests/testthat/test-golem_utils_ui.R
Labels: priority: high, type: enhancement

#54 Add testing for data functions types
  tests/testthat/test-app.R
  tests/testthat/test-fct_fft_data.R
  tests/testthat/test-fct_gpps_data.R
  tests/testthat/test-mod_gpps.R
Labels: priority: high, type: enhancement
